<?xml version="1.0" encoding="utf-8"?><Database Name="CollectionWeek" Class="collectionWeekDBMLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=CollectionWeek.db.3417772.hostedresource.com;Initial Catalog=CollectionWeek;Persist Security Info=True;User ID=CollectionWeek" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CollectionWeekConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.t_User_Log" Member="t_User_Logs">
    <Type Name="t_User_Log">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Zone" Member="Zones">
    <Type Name="Zone">
      <Column Name="ZoneID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Zone" Member="Zone1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>